name: fitapp-astro-frontend
services:
  astro:
    build: . # use Dockerfile to build the image
    ports:
      - "4321:4321" # default Astro ports
    volumes:
      - ./:/app:rw # bind mount: lokales Repo -> /app im Container
      - /app/node_modules
    networks:
      - fitapp-network

  nginx:
    image: "nginx:stable-alpine-slim"
    ports:
      - "8080:80" # host : container
    depends_on:
      - phpfpm
    networks:
      - fitapp-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # map file on host to file in docker container -> changes will be reflected in the container
      - ./src/data:/var/www/data:ro # map files on host from data directory to the location in the nginx server in the docker container

  phpfpm:
    image: bitnami/php-fpm:latest
    networks:
      - fitapp-network
    volumes:
      - ./php_script/calculate_bmi.php:/var/www/html/calculate_bmi.php:ro

networks:
  fitapp-network:
    external: true
